### ISSUE TITLE
Add a section for AEM as a Cloud Service

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/core-services.en#18]
Since the release of AEM as a Cloud Service, the users and groups are now managed via the Admin Console as well as the other Experience Cloud solutions. 
It would make sense to have a section for the same in (1)
And in this section, we should reference the section in the AEM as a Cloud Service documentation (2)

(1) https://docs.adobe.com/content/help/en/core-services/interface/manage-users-and-products/admin-getting-started.html 
(2) https://docs.adobe.com/content/help/en/experience-manager-cloud-service/security/ims-support.html#managing-products-and-user-access-in-admin-console 

[Logged By Support]

**Comment by BlakeFrei** [comment]
Fixed. Thanks!
