### ISSUE TITLE
The links do not work

### ISSUE THREAD

**Issue by kritikality** [AdobeDocs/core-services.en#24]
Issue in help/interface/cookies/cookies-thirdparty.md

The link to the Experience Cloud ID Service cannot be found
https://docs.adobe.com/content/help/en/id-service/using/implementation-guides/implementation-guides.html - 404

**Comment by bbringhu** [comment]
@BlakeFrei - The link should be here:

https://docs.adobe.com/content/help/en/id-service/using/implementation/implementation-guides.html
