### ISSUE TITLE
See IMS Support for AEM as a Cloud Service - Link Vandalized on Page

### ISSUE THREAD

**Issue by tbenson-adobe** [AdobeDocs/core-services.en#25]
Issue in help/interface/admin-getting-started/admin-getting-started.md

**Comment by BlakeFrei** [comment]
@tbenson-adobe This issue is fixed. Can you close? Thanks

**Comment by tbenson-adobe** [comment]
I don’t know the process to close the ticket – please close on my behalf.  Thanks!

**Comment by BlakeFrei** [comment]
@tbenson-adobe thanks, can do. I wasn't properly hooked up to this public git, so pubic issues weren't getting to me. Sorry for the delay. I now can close the issues. Take care. - Blake
